### ISSUE TITLE
Caching issues with use of query args

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#10]
[Filed on behalf of Christian at Akamai]
Perhaps it will be good to mention that use of query argument will prevent caching, for example, in the browser, an enterprise or an ISP

**Comment by wilaw** [comment]
Good point. We should add a note that CDNs may wish to explicitly exclude common-media-client-data from any cache key. Will CDNs have the ability to do this? i.e will it be a binary setting to exlude all query args form the cache key or just certain args?

**Comment by acbegen** [comment]
I think a binary switch is better and simpler to implement, at least for the initial version. On adding the note, absolutely as this may not be clear to everyone who is reading the spec.

**Comment by wilaw** [comment]
Added "The server MUST explicitly exclude common-media-client-data query arguments from any cache key.". Feedback?

**Comment by wilaw** [comment]
Edited to remove normative statement and replace with "Note: any caching proxy should be aware that the Common-Media-Client-Data payload will be constantly changing and therefore has the potential to pollute cache keys. Implementers may wish to exclude common-media-client-data query arguments from any cache key. "
