### ISSUE TITLE
Organize Reserved Keys section of document by Header Name instead of alphabetical for all keys

### ISSUE THREAD

**Issue by glenng1215gh** [cta-wave/common-media-client-data#111]
The document may read easier if the Reserved Keys section had  a separate table for each of the 4 Header Names:
CMCD-Request
CMCD-Object
CMCD-Status
CMCD-Session

This would help emphasis the importance of these scoping constructs (request vs session, for example)

**Comment by PCaponetti** [comment]
We will re-organize the document by header name. Once done, we can mark this complete.

**Comment by wilaw** [comment]
Actually I'm not a fan or organizing by header for the following reasons:
1. That breakdown would not make sense for Query ARG of JSON based reporting , which does not use headers.
2. More often than not, I am scanning the table looking for the definition of a particular key. It is far easier and faster to do that in alphabetic order than by scanning 4 tables of having to remember which key goes with which header.

**Comment by PCaponetti** [comment]
In group meeting, consensus achieved that given the comments above we will preserve a single table with alphabetical order.

Not opposed to making the document more readable, but not convinced that sharding by header is the right way.
