### ISSUE TITLE
Specify expected handling for  play continuation via casting (via AirPlay, Chromecast, etc...)

### ISSUE THREAD

**Issue by glenng1215gh** [cta-wave/common-media-client-data#112]
Version 1 was silent on this topic. I think it's worth having a section in the specification that addresses how CMCD should support casting, where playback is continued on a separate device such as an AppleTV or a Chromecast receiver.

Topics to consider:
- Should a new sessionID be generated by the casting receiver, or should the original playback session be passed through?
- Should the concept of a multi-device play be introduced, allowing QOS to be tracked across the transition?

**Comment by PCaponetti** [comment]
From a QoE perspective, having separate session IDs for different devices used across a single playback is not a hinderance. It could be used for content analytics, or other use cases, but the value is not closely aligned with the mission of CMCD to the degree necessary to warrant the cost of creating this linkage across devices.

Adding a mention in the document about casting across devices necessitating separate session IDs.

Changed the session ID language to ```A GUID identifying the current playback session. A playback session typically ties together segments belonging to a single media asset being played on a single device. Maximum length is 64 characters. It is RECOMMENDED to conform to the UUID specification [7].```
