### ISSUE TITLE
Definition around use of CMCD for beacons enabling out-of-band QOE Reporting

### ISSUE THREAD

**Issue by glenng1215gh** [cta-wave/common-media-client-data#113]
While CMCD version 1 defines a JSON format for the payload, it does not fully address the use case where the primary goal is to report player-side QOE data out-of-band to an analytics service, one that is typically independent from any of the CDNs. In this use case, player QOE data tends to be session and time-interval based as opposed to based around individual media segment requests.

With a few additions, CMCD can essentially also become a player QOE beaconing standard. A beacon would be defined as a set event-oriented beacon types, with each beacon type containing a set of CMCD keys. A proposed set of beacon types could like something like this:

**playback-start**
Issued at play start with all of the CMCD-Session keys and selected CMCD-Object keys such as Top bitrate (tb)

**playback-end**
Issued at play end with the CMCD sessionID (sid) key

**playback-error**
Issued whenever the player encounters a playback error. payload would carry an error identifier & data (TBD)

**playback-stall**
Issued whenever the player encounters a buffer stall. contains CMCD keys such as br,mtp,ot,pr,rtp. It would also be useful to capture duration of the stall, either on this event (posted when the stall ends), or with an additional **playback-resume** event.

**playback-heartbeat** 
Issued on a time interval defined either by the player or the analytics service that is is reporting, with a typical interval around 30 seconds. Metrics such as bitrate, throughput, and buffer length would represent the averages over the reporting time interval. Contains CMCD keys such as br,bl,mtp,ot,pr,rtp

Some may argue that this is beyond the scope of CMCD, but it could bring value to the overall ecosystem. For example, the existence of a QOE beaconing standard could eliminate the need for QOE vendor-specific player plugins, with players and QOE analytics backends all understanding the same beacon specification.

**Comment by PCaponetti** [comment]
The notion of batch reporting came up in the 2023-11-02 meeting that potentially overlaps here.

**Comment by glenng1215gh** [comment]
Additional events that could be captured with these beacons:
- Rendition switches
- Player-initiated mid-stream CDN switches

**Comment by acbegen** [comment]
What is the relation of this to [CTA-2066](https://github.com/mlevine84/CTA-2066_Public_Version/blob/master/CTA-2066_Public_Version.pdf)? There are companies who have been using 2066 definitions and if we introduce new definitions here, would not that cause more confusion/interop issues?

**Comment by glenng1215gh** [comment]
I was unaware of CTA-2066. good work there streaming QOS events and metrics. What I don't see there is a definition of a transmission protocol or format for these events (JSON or XML posts over HTTPS, for example). Now that I see CTA-2066, that should certainly form the basis of a QOS beaconing standard, and should be harmonized with CMCD to use common names and definitions whenever possible. Is any new work ongoing on CTA-2066?

**Comment by acbegen** [comment]
Yup, 2066 did not bother with the transport side of the metrics but then when we defined CMCD, we did not really tie it to 2066, either. Coming from the same organization, these two specs could have been used together in a better way. I think this warrants some discussion in the next call. 2066 was not a product of the WAVE project but it is from R04 WG20 Streaming Media Quality of Experience (QoE). @mlevine84 and @wilaw might say more. Another good read from Akamai is [here](https://www.akamai.com/site/it/documents/white-paper/measuring-video-quality-and-performance-best-practices.pdf).

**Comment by acbegen** [comment]
Wow, this is pretty detailed. Maybe, our first step should be to acknowledge whether there is a need for this (or not). Depending on that, reviving/revising 2066 might be one of the next steps.

**Comment by nicolaslevy** [comment]
I completely agree with @acbegen on the need to determine if this expansion of CMCD is the way we want to go. My perception is that there's definitely a lot of enthusiasm for evolving CMCD into a standard with more capabilities for QoE reporting. 

However, if we decide to go down this path, I think it's important to think about CMCDv2's scope and ensure it doesn't become overly complex for implementation. We wouldn't want a standard that's so intricate that it ends up not being adopted. Planning for incremental enhancements, adding use cases (more information) in future versions as the industry adopts CMCDv2's new functionalities, could be a good approach.

**Comment by glenng1215gh** [comment]
to minimize overloading CMCD, we could either evolve CTA2066 into a beacon standard (with transmission semantics), or develop a new standard specific only to beacons, leveraging CTA2066 event & metric definitions. either way, CTA2066 and CMCD2 need to be harmonized, using common vocabulary whenever possible.

**Comment by wilaw** [comment]
As a summary of the decisions reached on this issue:

1. We'll not attempt to make CMCD v2 a stand-alone replacement for analytics vendors data collection. This goal would bloat the key dictionary, has little chance of completely succeeding and would threaten the core attribute of CMCD v1 which is simplicity  - of both comprehension and implementation. 
2. We will investigate being able to generate a sub-set of interval-based (rather than request-based) metrics which can be reported independently of the media requests. This concept is captured by issue #117.
3. We will add keys to enabled improved QoE metrics for the request-based reporting.
