### ISSUE TITLE
video start-up time and start-up failure.

### ISSUE THREAD

**Issue by ZmGorynych** [cta-wave/common-media-client-data#115]
For analytics / KPI purposes we need to know whether the attempted playback start-up failed or succeeded, and if yes -- how long did it take.
Proposal: introduce new keys, `vst`, `vsf`, and `ttfn`.
vst: number of fractional seconds (msec precision) from the moment a manifest was requested till the first frame was rendered
vsf: number of fractional seconds (msec precision) from the moment a manifest was requested till the client gave up
ttfn: flag indicating that a session is closing (e.g., the player gave up or was closed by the user)   

ttfn and vsf can only be implemented with beaconing -- a player giving up on a session won't issue manifest or segment requests.

**Comment by PCaponetti** [comment]
Note overlap with #78 (add media start time with comments to add other things).

**Comment by PCaponetti** [comment]
The missing bits are the state changes, and these can be handled with the new player state key added as part of the beaconing issue.
