### ISSUE TITLE
Connections to multiple servers

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#12]
[Filed on behalf of Christian at Akamai]
It may be relevant to have some information about what the client should do if it has connections to multiple servers. Or maybe sometimes try out different servers to measure their performance. For example, is the mtp field for the current server?

**Comment by pankaj-giter** [comment]
Valid point. Players must have connection specific 'mtp' value

**Comment by wilaw** [comment]
Does not server already have ping RTT info to client? What would server do with this MTP value if it was communicated?

**Comment by wilaw** [comment]
MTP value must be measured against existing server, or it should not be sent.

**Comment by wilaw** [comment]
Added " If the client is connected to multiple servers concurrently, it must take care to report only the throughput measured against the receiving server."
