### ISSUE TITLE
Top Encoded Bitrate may leak device data in its response. 

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#123]
It occurs to me that the top [aggregate] encoded bitrate field has the potential to decrease entropy in a fingerprinting vector targeting CMCD.

The draft specification mentions this value should consider the “current codec, licensing, and sizing constraints” of the playback environment. A privacy-minded player might be inclined to forgo reporting such a value. But I recognize how valuable this value is to an observing provider - maybe there’s a way its language can be relaxed.

Jordan
(Apple)

**Comment by PCaponetti** [comment]
Jordan: with this information you may be able to figure out which of a bucket of devices might be playing this content
Will: have you thought on how to relax the language without hurting QoE signal?
Jordan: Seems the signal and leak are intricately linked
Will: what if we just say it is the highest bitrate in the manifest? Could still be useful signal.

Changes to spec in following comment

**Comment by wilaw** [comment]
Adjusted top encoded bitrate definition to be

> The highest bitrate rendition in the manifest or playlist. This SHOULD be derived from playlist/manifest declarations, or it MAY be estimated by the player. If the playlist declares both peak and average bitrate values, the peak value MUST be transmitted. This top bitrate MUST apply to the object type being requested. Requests for video objects MUST specify the top video bitrate and requests for audio objects MUST specify the top audio bitrate. This value MUST NOT be sent for objects which do not have an object type of  ‘a’, ‘v’, ‘av’ or ‘c’. 


Adjusted Top aggregated encoded bitrate

> The highest aggregated bitrate rendition in the manifest or playlist. This SHOULD be derived from playlist/manifest declarations, or it MAY be estimated by the player. If the playlist declares both peak and average bitrate values, the peak value MUST be transmitted. The aggregate encoded bitrate is of the complete media object including all object types. This value MUST NOT be sent for objects which do not have an object type of  ‘a’, ‘v’, ‘av’ or ‘c’. This value MUST NOT be sent if the top encoded bitrate is known.
