### ISSUE TITLE
Need clarification on Session ID and Content ID considering Interstitial content and casting scenarios

### ISSUE THREAD

**Issue by nicolaslevy** [cta-wave/common-media-client-data#125]
Considering that content may have HLS Interstitials or DASH Alternative MPD, or that a user may cast content with Chromecast or AirPlay, I believe it is necessary to clarify what the value of the session ID and Content ID should be in these scenarios to avoid confusion.

Current Session Id description:
> A GUID identifying the current playback session. A playback session typically ties together segments belonging to a single media asset. Maximum length is 64 characters. It is RECOMMENDED to conform to the UUID specification [7].

Current Content Id description:
> A unique string identifying the current content. Maximum length is 128 characters. This value is consistent across multiple different sessions and devices and is defined and updated at the discretion of the service provider.

**Comment by PCaponetti** [comment]
Will: I agree with the proposal
Sebastian S: +1

Updated Session ID content to say
```A GUID identifying the current playback session. A playback session typically ties together segments belonging to a single playback session. This session may comprise the playback of primary content combined with interstitial content.  This session is being played on a single device. Maximum length is 64 characters. It is RECOMMENDED to conform to the UUID specification [7].```
