### ISSUE TITLE
Introduce TTLB and TTFB

### ISSUE THREAD

**Issue by ZmGorynych** [cta-wave/common-media-client-data#127]
Add TTFB/TTLB to Mode 2 to be able to look at failure causes
Compaction -- ttfb / title as duration

**Comment by PCaponetti** [comment]
Potential uses of the mode 2 transmission (coupled to a media object request but sent after response) go beyond just latencies.

Decided to add the following the to document: 

Response Code: The response code received when requesting a media object. In a redirect scenario, this would be the final response code received. A value of 0 SHOULD be used to indicate that a response was not received.

Time to first byte: The elapsed time between when the request was first initiated (captured in ts) and the time the first bytes of the response are received. This value should only be reported if it is known. Absence of this key does not indicate that the response was not received.

Time to first body byte: The elapsed time between when the request was first initiated (captured in ts) and the time the first bytes of the response body are received. This value should only be reported if it is known. Absence of this key does not indicate that the body was not received.

Time to last byte: The elapsed time between when the request was first initiated (captured in ts) and the time the response body is fully received. This value should only be reported if it is known. Absence of this key does not indicate that the response was not fully received.
