### ISSUE TITLE
Better naming for the modes?

### ISSUE THREAD

**Issue by acbegen** [cta-wave/common-media-client-data#128]
Mode 1: Default mode
Mode 2: Per-response mode
Mode 3: Per-interval mode

I know mode 3 is also triggered upon state changes, but then the term "interval" still applies IMO.

**Comment by ZmGorynych** [comment]
Mode 1: "Request mode"
Mode 2: "Logging mode" (we can do batching, so per-response is a misnomer)
Mode 3: "Trigger mode"

**Comment by PCaponetti** [comment]
Paul to take some homework to come up with 5 options here.

**Comment by nicolaslevy** [comment]
Mode 1: request mode
Mode 3: state-interval mode

**Comment by wilaw** [comment]
+1 to https://github.com/cta-wave/common-media-client-data/issues/128#issuecomment-2194998267

**Comment by PCaponetti** [comment]
I do really like the suggestion from Nicolas and enhancement from Will. In the interest of completeness and finishing my homework, here are a few more ideas:

1) Standard
2) Remote
3) Summary

1) Inline
2) Out of band (OOB)
3) Snapshot

1) Piggyback
2) Independent
3) (one of the ones from above?)

To be clear, I'm not liking any of these as much as what has been suggested already.

**Comment by PCaponetti** [comment]
Going with Nicolas' original request, as the `on-` prefix led to a bit of confusion and bikesheding. We can change later if there is genuine confusion.

**Comment by piersoh** [comment]
1. origin
2. alternate
3. alternate-state-periodic (alternate-sp)

**Comment by wilaw** [comment]
We decided on

- Request Mode
- Response Mode
- State-Interval Mode

Also tightened language around timing , reporting delay and recommended intervals.
