### ISSUE TITLE
Downloading-only player state?

### ISSUE THREAD

**Issue by acbegen** [cta-wave/common-media-client-data#129]
The player might be downloading content for offline playback. Should not we have a state reflecting this for "sta"?

**Comment by PCaponetti** [comment]
David: can have download functionality in a player, but likely it is done outside the player. Maybe too niche. Would it be full files or segmented?
Rob w: can be segmented. 
Paul: data could be noise, not sure of a use case
Nicolas: Could be used for prioritization
Paul: agreed, and when this is noted no other keys are useful, and can be misleading so we should note that when downloading just send the flag

Tie this to the fate of #120 as we could fit this into that key. If that issue doesn't go through, we can add a bool flag.

**Comment by acbegen** [comment]
The main use case for this was the server could prioritize accordingly any client that is in download-only state (lower prioritization compared to playing clients).

**Comment by wilaw** [comment]
We added a "d: preloading" state which could be used to signal the download. A download would be detectable as a preloaded without a following starting or playing state.
