### ISSUE TITLE
Server response header to indicate support of CMCD

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#13]
[filed on behalf of Christian at Akamai]
You could consider introducing an HTTP response header that a server SHOULD send to indicate that it supports receiving the data. In this way a client could avoid sending a lot of data if the server cannot consume it anyway. And avoid preventing caching or doing preflight requests as mentioned above.

**Comment by pankaj-giter** [comment]
This makes sense especially when client is using request headers and has to contend with CORS (OPTIONS request).
One can argue that we may want the server to be more transparent about which specific attributes of CMCD it supports or not, but that would be overreaching at this point and an unnecessary rathole and complexity.

**Comment by wilaw** [comment]
Options here to
a) CDN must advertise that it wants the data before the client sends it
b) CDN can turn off the data if it doesn't want it
c) CDN can always be sent the data by the client.

Group decided to opt for simplicity with initial release. We may want to revisit this requirement in the future if there is push-back from CDNs. Also, the Common-Media-Server-Data may wish to address this.
