### ISSUE TITLE
Clarification on the use of the msd (Media Start Delay) Key in CMCD using request-mode

### ISSUE THREAD

**Issue by nicolaslevy** [cta-wave/common-media-client-data#136]
### Context:
While implementing the `msd` key as part of our integration with the Common Media Client Data (CMCD) specification, we encountered a few questions regarding the correct usage and expected behavior of this key. We understand that our team might be among the first to implement this specific key since it is part of a still-evolving standard.

`msd` key:
> Measures the initial delay in wall-clock time from when a player is instructed to play media for a given session to when any media begins playback, whether it be primary content or interstitial content.

#### Request Type for msd Parameter:
Using request-mode, once we have obtained the value for `msd`, in what type of request should this parameter be included?Should it be sent once, or in all media segment request (e.g., video, audio)?

Proposed Implementation:
we are considering the following implementation strategies, and probably we will implement Option A, do you have any advice?:
- Option A: Send the msd key once, in the first CMCD request after the data is available, regardless of the type of object being requested (e.g., audio, video, manifest).
- Option B: Continuously send the `msd` key for the duration of the session. However, this might add unnecessarily bytes to the wire.

#### Edge Case Consideration:
Using request-mode, in a scenario where the video content is very short and all segments are downloaded before the user starts playback, would this mean that the `msd` key would not be sent at all? Is there a recommendation to handle this situation? 

Note: I think there might be no solution for this, and we should recommend also use state-interval mode if you know you could have this kind of scenarios.

**Comment by wilaw** [comment]
I would go with option A - send the msd key once per sessionID|contentID tuple, and send it on whichever request (audio, video, captions , playlist) occurs next _after_ startup is complete. 

For the edge case, I'd suggest reporting a msd of close to zero, as that is what the user effectively experiences. We should explicitly address this case in the spec.

**Comment by nicolaslevy** [comment]
> For the edge case, I'd suggest reporting a msd of close to zero, as that is what the user effectively experiences. We should explicitly address this case in the spec.

Yes, we should address this. I agree that if playback occurs, then it will be zero or very close to zero. What I see as a potential pain point is that sending a value if all segments are downloaded may not be accurate if the user decided not to play the video. I think the data should only be sent if there is certainty about it.

Side note: These edge cases are a headache but also quite fun :)

**Comment by wilaw** [comment]
Added new text to address this case: 

> Measures the initial delay in wall-clock time from when a player is instructed to play media for a given session to when any media begins playback, whether it be primary content or interstitial content. This value SHOULD be the time difference bewteen the "starting" and "playing" states. 
> This key MUST only be sent once per Session ID and MUST be sent for each reporting mode which is active within the player.
> For request and response reporting modes, this key SHOULD be sent on the next media object request following successful startup.
