### ISSUE TITLE
Should we have a key for visibility of the player of a player being backgrounded?

### ISSUE THREAD

**Issue by PCaponetti** [cta-wave/common-media-client-data#137]
In conversations about player state the state of being backgrounded and/or not visible came up. Should we have signal for this?

Options discussed so far:
- another state in the player state key: this would mean it is mutually exclusive with other keys and only reported on state-interval mode which misses out on value to request mode where dynamic prioritization of requests can be done
- a separate key to report in any mode: we do get the ability to prioritize requests here, but it will break with the paradigm of request and response mode tying the data to the point in time the request was sent instead of data about the segment being requested. It also leads to incomplete data as transitions to and from backgrounded mode can/will happen in between segment requests.

**Comment by alficles** [comment]
Can we double-check whether this is likely to have privacy concerns around this? It might be worth at least a sentence or two in the Privacy Concerns sections.

The basic idea is that people don't necessarily intend to expose this information and precisely what and how people are viewing the content. But this is also quite useful for determining if video rebuffering is impacting a human.

**Comment by wilaw** [comment]
Paul: asked Rob
Rob: this info is critical and we should include, even if Apple have issues. 
Paul: we need a new key.
Will: can we signal put to sleep versus backgrounded
Rob: whats the right amount of specificity?
Nicolas: what does visible mean?

**Comment by PCaponetti** [comment]
Added the following key to the spec:

Backgrounded (bg): The player is currently in a state that is not visible to the user. This key SHOULD only be sent if it is TRUE. If the visibility state of the player is not known this key SHOULD not be reported.
