### ISSUE TITLE
Add playhead position to facilitate ad reporting via cmcdv2

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#142]
The SVTA Advertising Group  has a proposal for Client Guided Ad Tracking and is also working on an Ad Signaling standard. Rather than introduce another beaconing activity for the player, it could simply leverage CMCv2 state-interval mode to send the data to a collection point. The only attribute missing to enable this is some means to report the playhead position of the player. 

Proposal: add a new key called "Playhead position". Its abbreviation would 'pp', it would be attached to CMCD-STATUS header and would report the playhead position in media time seconds. 

For a VOD asset, media time is a clear value. For a live asset, player UI may express position as distance behind live, or else elapsed time since the session started, so there needs to be some thought as to how to express live playhead position consistently.

**Comment by olivier-yospace** [comment]
At the moment, for live streams, we request the player to use the start time of the first segment returned in the first manifest as its reference time (t0). The reasoning is that this is similar to how VOD works.
And just like for VOD, player should then provide the playhead position as an offset to that reference time (t0).

**Comment by ZmGorynych** [comment]
1. I think it's a good idea overall
2. What is the frequency of this? Would you do this on start/end of the ad playback? Would you need quartiles?
3. Is it intended only for the ad itself, or also for the normal entertainment content?

**Comment by olivier-yospace** [comment]
Thanks Alex for having a look.

The goal would be to fire all Ad Beacons (including the quartiles) based on the playhead position. We think that a good default value would be 1s.
Another goal that we have is to allow for the API to provide Ad Break Metadata to the player. This would allow the player to know that it is entering an Ad Break (for example to display the duration of the Ad breaks). This could also be used by the player to retrieve the beacons and fire them client side (if needed).
The API would be used for both SSAI and SGAI. In SSAI, the player shouldn’t be aware when a period is an Ad or content, so we think it’s best that it calls the API all the time (including normal entertainment content). 

Regards,

Olivier

**Comment by wilaw** [comment]
> re We think that a good default value would be 1s.

@olivier-yospace  - are suggesting that the player constantly fire SI reports at 1 s intervals both when playing primary content and interstitials? This seems excessive. I think we need another scheme. Maybe it increases its rate during interstitials only?

**Comment by PCaponetti** [comment]
Will: Could maybe use ts (timestamp) and do analysis
Paul: but it might be tough to get playhead position due needing durations of pauses, diffs from seeks, etc.
Nicolas: Maybe we shouldn't invent something where SVTA may know the data needed.
Nicolas: Also, we should add interstitial boundary to set of states (will open issue)
Piers: How does playhead position report in an interstitial?
Paul: What are the use cases? Hotspots in content for different actions (like seeks, pauses, etc)?
Will: Valid use case, do we use seconds or milliseconds (Paul, Chris, Alex: subsecond is useful). Moving to int milliseconds.

Added the following language for new key `pp` WITH some TODOs:

```The media timestamp, expressed in milliseconds, which is being rendered to the viewer when the report is made. For Response and State-Interval modes, this corresponds to the media time that was rendered at the wallclock time reported by the timestamp field. 
Note: for live stream playback, media time is represented as TBD. 
Also, we need to solve the problem of how to make quartile reports or equivalent during interstitial playback.
```


Nicolas Levy to go to SVTA to ask what data will be useful here.

**Comment by ZmGorynych** [comment]
Proposal: for all media represent media time as a presentation time (i.e., PTS) of the currently displayed picture, in media timestamp units. 
This is simple enough to derive uniformly, but non-trivial to interpret.

**Comment by ReinhardG** [comment]
From a Player PoV, we support the idea of facilitating ad reporting via CMCDv2. This may simplify workflows and avoid redundant reporting. 

Regarding reporting intervals, our current Analytics implementation reports events in real-time (if they happen) or heartbeats in 60-second intervals, which turned out to be a good strategy for production environments. We also follow this approach for ad signaling. So, I suggest considering a dynamic approach for interstitials.

**Comment by olivier-yospace** [comment]
Hi,

From a SSAI/SGAI perspective, 60-second intervals could work for us, provided that we also get a real-time notification when player switch to interstitial and start a new period.

However, an alternative could be that the CMCD data is attached to the manifest request from the player using the query parameter expansion system.
This would mean that either events would not be reported in real-time which isn’t critical for us as long as it is within a segment duration. 

What do you think of this alternative?

Thanks,

Olivier

**Comment by nicolaslevy** [comment]
I have a proposal for this Interval stuff resolution that are consequence of this this ideas:
* https://github.com/cta-wave/common-media-client-data/issues/149
* https://github.com/cta-wave/common-media-client-data/issues/148
* https://github.com/cta-wave/common-media-client-data/issues/146

If we extend the State interval mode to be more generic and trigger an event when an Interstitial is detected ([as described on the ticket](https://github.com/cta-wave/common-media-client-data/issues/148), and we allow the Ad Tracking system (third party endpoint) to set the interval time via the HTTP response, the Ad Tracking system will be able to increase the interval during the Interstitial duration. The Ad Tracking will be able to control the "data resolution" during the interstitial period and we don't need to specify any especial rule for Tracking Ads.

![image](https://github.com/user-attachments/assets/34620b2d-e54c-4be9-8490-f7019cd30e7e)

**Comment by olivier-yospace** [comment]
Thanks Nicolas,

An important point for us is to not only support SGAI (with alternativeMPD) but also SSAI.
So we would also like to also cover a change of period (DASH) and a DISCONTINUITY marker (HLS) as this could mean the beginning of an Advert.

**Comment by nicolaslevy** [comment]
> An important point for us is to not only support SGAI (with alternativeMPD) but also SSAI.
So we would also like to also cover a change of period (DASH) and a DISCONTINUITY marker (HLS) as this could mean the beginning of an Advert.

Got it! I think this could be something to cover somehow in a new CMCD Key and if [Extend State-Interval Mode to Support more Playback Events](https://github.com/cta-wave/common-media-client-data/issues/148) success, a event could be sent when a change in that new key happens.

**Comment by PCaponetti** [comment]
Added the following text, will revisit next meeting:

```When reporting to a third party backend, a player SHOULD implement retry, backoff, and other mitigations for overload scenarios.```

**Comment by nicolaslevy** [comment]
Now that I recap about this ticket, this last acction item was already added in the document when discussing https://github.com/cta-wave/common-media-client-data/issues/146 but that changes are not the main issue of this ticket. 

We should continue discussion about `play head position` key

**Comment by wilaw** [comment]
Will: we can just let the player report the media playtime that is likes for live, as long as it is consistent. The analytics system can figure out the position in the media. 
Paul: how does this tie to different ad insertion systems
David: gave an overview of SSAI vs SGAI. We do need to unify time. Could do it as Player date time conversion. 
Alex: we could do TFDT of the media segment. 
Paul: can we keep it simple, analytics and player are controlled by the same entity. 
David: we need to make it consistent as distributors don't control all their players. 
Alex: we have two timelines - media time and real-time. For ad reporting we just need media time. 
Will: we have event when we enter an interstitial and also when we leave it
Nico: we don't need quartiles then. We have events.


Proposal: We allow the player to report playhead position and then use events to report when we exit and leave ads. or seek out of them.

**Comment by wilaw** [comment]
Changed: playhead position to playhead time. 'pt' . Left definition consistent between VOD and LIVE.
