### ISSUE TITLE
Extend State-Interval Mode to Support more Playback Events

### ISSUE THREAD

**Issue by nicolaslevy** [cta-wave/common-media-client-data#148]
In the current definition of the State-Interval Mode, it was established that the player generates and sends CMCD to a third party whenever there is a change in the Status ('sta' key) and at specific time intervals (for example, every 30 seconds).

This ticket proposes extending this definition so that this mode generates and sends CMCD not only in these two cases.
By defining a set of events, we can expand the State-Inteval Mode to be useful for other scenarios, such as Ad tracking (https://github.com/cta-wave/common-media-client-data/issues/142).

Specifically, the proposal is that events triggering the sending of CMCD include:
* Rename the "State-Interval Mode" to "Event Mode" or "Playback Event Mode."
* The "Event Mode" send CMCD on:
  * Change in player state ('sta' key)
  * Change to an interstitial or Main content ('int' key)
  * Change in content ID ('cid')
  * Occurrence of an error code ('ec')
  * Passage of a certain amount of time as defined by the application (the current definition of Interval for the State-Interval Mode)
* The keys (events) that triggers are configurable enabling for example use cases like Ad Tracking systems to configure only this mode only when 'cid' or 'int' changes.

**Comment by PCaponetti** [comment]
Paul: I agree with adding more keys to trigger state interval mode requests, although it does make things messier. The case for adding trigger fields is to handle more use cases:
- more visibility into critical moments, like change to interstitial or new main content
- more visibility into non-fatal errors
- more use cases with potentially new trigger fields
The downside is mostly complexity. Adding complexity for player builders and adding cognitive load for new combinations of data causing requests. Load is not as much of a concern because batching is already urged in the spec.

**Comment by PCaponetti** [comment]
Sebastian S: Are you looking to make certain keys that are triggers for State-Interval mode required?
Will: Like this very much, but would not make events required
David H: need to be unified on events across players
Paul: If we don't have all the events required, can we enter a state that is not supported by a player and have the consumer of CMCD information not have sufficient information or confidence to know what is happening? We may have to make certain or all triggers required at least inside of equivalence classes.

There are a few curiosities around content ID change and interstitial:
- how do we know all ads will have different content IDs?
- how could a player know generically if it is playing an ad or main content?

Mocked up some text to see where the issues are

**Comment by wilaw** [comment]
Consensus around renaing to EVent mode. Document updated. Added new event key 'e' with following token definintion

This key MUST only be used in Event mode. 
ps - play state change. This token MUST be accompanied by a 'sta' key carrying the new state. 
e - the player has experienced an error. This token MUST be accompanied by a 'ec' key defining the player error code. 
t - time interval. The interval at which these reports are made is application-defined. A default interval of 30 seconds SHOULD be used if no explicit application interval is provided. Short form content may wish to use a shorter interval. An application-defined interval of zero should be interpreted as turning off interval event reporting. This event MUST be supported by all players that support Event mode. 
c - content ID has changed. This token MUST be accompanied by a 'cid' key defining the new content ID. 
i - the player has entered interstitial playback if this event is accompanied by the 'int' key and exited interstitial playback if not.
