### ISSUE TITLE
Registry for extensions

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#15]
If a 3rd party defines extensions, where can they be registered?

**Comment by acbegen** [comment]
I vote for IANA. simple, free, open and easy to maintain. See https://tools.ietf.org/html/rfc8126

**Comment by wilaw** [comment]
Do we need to register extensions? Won't most extensions be private implementations? Whatn is a good use case of an extension that should be registered?

Additionally, we have this text around extensions "Custom key names may be used, but they MUST carry a hyphenated prefix to ensure that there will not be a namespace collision with future revisions to this specification.". So0 3rd parties can define extensions that won;lt interfere with reserved or other 3rd party extensions as long as they use a custom prefix.

**Comment by wilaw** [comment]
Group discussed at length and agreed to
1. Add a recommendation around reverse-DNS naming for custom key prefixes.
2. Added a version key.
