### ISSUE TITLE
Are SU and BS required when a player specifically blacklists them?

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#152]
[Question form dash.js call today]

As a V2 update, we decided to mandate SU and BS be added if they are TRUE.

However if a player is given a config that specially blacklists those keys, then what should happen?

**Comment by PCaponetti** [comment]
Paul: Thinking that this is already specified by saying keys are required, adding something may be redundant. possibly if we have an example configs section in the future.
Gwendal/Nicolas: We cannot enforce this or know what the player behavior is in the absence of the keys.

The room feels that an implementation of CMCD v2 that allows deny-listing of keys that are required is already an invalid implementation and to say so explicitly would be redundant.
