### ISSUE TITLE
Device, Content, Session IDs

### ISSUE THREAD

**Issue by acbegen** [cta-wave/common-media-client-data#16]
There are some normative requirements in the document about these values. However, all these could be already set by external entities a priori for obvious reasons and I don't think the players should pick different values just for the sake of using CMCD. If that was not the intent, the normative language should be revised and a clarification note should be added.

**Comment by wilaw** [comment]
Intent is for normative constraints (64char length and no colon) to be broad enough that current identifiers in use would not need to be modified. We verified that session, device and content ids used by Hulu and JWplayer would meet these requirements.  Should ask other vendors if this is consistently true.

**Comment by wilaw** [comment]
Industry survey revealed that we could not identify a currently used sessionID which did not comply. Will leave as is.
