### ISSUE TITLE
Measured tput

### ISSUE THREAD

**Issue by acbegen** [cta-wave/common-media-client-data#17]
Players can measure tput in a variety of ways and even under the same circumstances they will end up with different results. So, without a common way of measuring tput, what do we expect the CDN/server to do with this value?

**Comment by pankaj-giter** [comment]
+1 at least on how the server is supposed to consume this data.

**Comment by wilaw** [comment]
Log files could should CDN estimate of throughput versus client view. Is this a sufficiently strong use case to warrant inclusion? Client throughout is already supplied through QoE metrics.

**Comment by wilaw** [comment]
Group agreed that it is useful for clients to report this data and for the CDN to log it, especially for post-delivery analysis.
