### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by acbegen** [cta-wave/common-media-client-data#18]
There are quite a few parameters that a bad-behaving client can use to cause issues for the servers and other clients. Do we plan to document the risks or what can be used to prevent them? Or shall we just say the assumption is we only have good clients and it is the CDN's responsibility to handle attacks?

**Comment by wilaw** [comment]
We are not naive in assuming that all clients are good. However, in looking at the spec, we don't believe the spec exposes any security issues _that are not already exposed_ to an edge server which answers all requests. For example, you could argue that the next-object-request could be used as an amplification attack by requesting a very large object. This is true, however nothing stops a bad client from simply opening two connections and making the same requests against the CDN edge. This is a problem CDNs must deal with today so we are not adding a new problem.

Steps taken to reduce security concerns
1. NOR - must be a relative path to the current request. This makes it harder to inject false requests to arbitrary objects. 
2. NOR - only one object can be requested. This lowers amplification opportunity.
3. All requests to the server are optionally executed by the server, meaning that a server can ignore them if it chooses for security concerns (rate-based threshold for example) and still be spec compliant.

**Comment by NEOAdvancedTechnology** [comment]
That sounds like a good thing to document in an informative fashion in the standard.

-Thomas

--
Thomas Edwards
VP Engineering & Development
Walt Disney Television
thomas.edwards@disney.com<mailto:thomas.edwards@disney.com>
+1-310-369-6696
10201 W Pico Blvd
Los Angeles, CA 90035

**Comment by wilaw** [comment]
Added a note to the server interpretation section.
