### ISSUE TITLE
No common-media-server-data?

### ISSUE THREAD

**Issue by acbegen** [cta-wave/common-media-client-data#19]
If the CDN servers will be "enhanced" to be able to know more about the clients' status, why would not they also be "enhanced" to send certain useful info back to the clients?

Example: The client indicates a nor value but the server may already have an alternative to that in the cache and can recommend it to the client.
Clients sends nor:rep3segment45.mp4
Server responds norr: rep4segment45.mp4 (Next object request recommendation)

I briefly touched on this in yesterday's call. This is why we designed 23009-5 (Server and Network Assisted DASH). See the attached figure for how SAND is supposed to be used. In other words, I am asking whether we should also define values for "Parameters enhancing reception - PER".

<img width="1204" alt="Screen Shot 2019-11-15 at 2 42 34 PM" src="https://user-images.githubusercontent.com/18185643/68941234-4fa6df80-07b6-11ea-8037-3ee1426b28f3.png">

**Comment by wilaw** [comment]
My intent is to establish a Common-Media-Server-Data specification, upon completion of the CMCD spec. I want to this to be outside of SAND - for several reasons a) it is not presentation specific b) it should be much simpler c) SAND has many IP declarations against it and is very unlikely to be deployed by CDNs at scale. Any origin that wanted to could support CMSD and SAND simultaneously. 

Current useful properties for CMSD to send are
1. Bandwidth estimate
2. Max player bitrate limit
2. Redirection suggestion

**Comment by wilaw** [comment]
Two clients can consume Common-Media-Server-Data  - one is a CDN edge (if the data is set by an origin) and the second is the player. The CDN edge can also set data. 

Proposal is to use a single spec to cover both use-cases, with key/value pairs that can be applied at either origin or edge. 

1. origin hint as to next segment
2. live or vod content
3. format - HLS or DASH, Smooth
4. Type of object - media seg, subtitles, init, playlist etc
5. Wallclock publish time of segment
6. Breadcrumb data 
7. How heavily is loaded, network or CPU

**Comment by heff** [comment]
I had a similar thought related to "The client SHOULD NOT depend upon any pre-fetch action being taken - it is merely a request for optimization."

It seems like the client would need to know when prefetching does and does not happen to accurately predict future requests.

**Comment by wilaw** [comment]
@heff - is comment above related to this thread (which is about a future server data standard), or was it intended to be feedback against CTA 5004 ?

**Comment by heff** [comment]
@wilaw I figured it was related because it would require the CDN to communicate back to the player. Maybe not.

**Comment by tonihei** [comment]
Additional information that may be helpful for a client:
 - Maximum suggested bitrate (as a control mechanism for the CDN to prevent overloading).
 - Information about which variants/representations of the next segment are already cached by the CDN edge. 
 - For how long the request has been held without transmitting bytes (e.g. for LL-HLS blocking requests)

**Comment by acbegen** [comment]
> @wilaw I figured it was related because it would require the CDN to communicate back to the player. Maybe not.

I believe @heff wants a flag or something similar from the server to the client indicating whether the segment was prefetched or not.

**Comment by wilaw** [comment]
The Common Media Server Data project has been started. The requests in this issue have been transferred to https://github.com/cta-wave/common-media-server-data/issues/1
