### ISSUE TITLE
Consideration of trends

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#2]
Filed on behalf of Michael Fay

Late to the game but I was curious if there is a possible consideration for TREND,

while trends can be extrapolated from a time series server side; is there any way that a single <Value> could be informed by its predecessor and inform GOOD or BAD from the previous reported <Value>?

Does/Could the client have awareness of what it submitted previously enough to say that certain <values> were better or worse than the previous submission?

For example
Measured Throughput Trend [good/bad from last sample]

Would this make decisioning faster?

**Comment by wilaw** [comment]
Will - trends difficult to define, also what would CDN do with info? 
Thomas Edwards - get more info from Fay.
JohnL - how much data would client need to keep?

**Comment by wilaw** [comment]
Cooper - could this in fact be the client summarizing its state - bad, neutral, good.

**Comment by wilaw** [comment]
Thomas - took AI to get in touch with Fay. Remind about buffer state, also ask about what CDN would do with this info if it had it.

**Comment by pankaj-giter** [comment]
Thomas: No feedback from Michael Fay yet. Proposed to close this ticket in next call if no update on this ticket from Michael Fay.

**Comment by wilaw** [comment]
Closing since no additional update.
