### ISSUE TITLE
Provide stream format type, as in HLS or DASH

### ISSUE THREAD

**Issue by pankaj-giter** [cta-wave/common-media-client-data#21]
CMAF will consolidate the segments under HLS and DASH and makes it difficult for a CDN to know the streaming format in use for purpose of reporting. It would be helpful if the spec could support an additional attribute coming from player to signal the stream format type as 'h' for HLS, 'd' for DASH, 's' for Smooth. 
(Intentionally not covering HDS)

**Comment by wilaw** [comment]
Added new streaming format key
