### ISSUE TITLE
Object-Type enumeration list - change to definition of "init" segment 

### ISSUE THREAD

**Issue by pankaj-giter** [cta-wave/common-media-client-data#23]
For TS init segments in HLS signaled via the #EXT-X-MAP tag in the HLS variant playlist, it would make sense to signal it as 'i' for init segments. However, the definition of 'i' reads "ISOBMFF init segment".
Can I propose a change in the definition as simply "init segment" ?

**Comment by wilaw** [comment]
Agreed and executed.
