### ISSUE TITLE
Playback rate = 1

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#24]
Playback rate description is currently "1 if real-time, 2 if double speed, 0 if not playing. Should only be sent if not equal to 1."  Mentioning 1 is encouraging people to send 1.

Maybe just: "0 if not playing, 2 if double speed.  Should not be sent if playback rate is 1x real-time"

Are there other playback rates we should be concerned about besides double?

Should "0" be sent during "buffer state" of "startup/initializing", "seeking", "buffer empty"?

**Comment by pankaj-giter** [comment]
For Q1: Suggested re-wording sounds OK
"0 if not playing, 2 if double speed. Should not be sent if playback rate is 1x real-time"

For Q2: The multiplier for the real time speed MUST be defined for this key. Example: 0.5 for half the real-time speed. 1.5 for 1.5x the real-time speed.

For Q3: The group decided on the following:
1/ Change the name of the 'playback rate' to 'target playback rate'
2/ Definition is updated to:
"Multiplier of real-time on playback rate when the playback rate is not 100% of real-time.
For example, 4 would mean playback rate of 400% of real time. 1 would mean playback rate equal to real time. If playback rate is 100% of real time, this key should not be sent."

**Comment by pankaj-giter** [comment]
Closing per above comment
