### ISSUE TITLE
Problematic incentives

### ISSUE THREAD

**Issue by alficles** [cta-wave/common-media-client-data#26]
Some of the existing fields, if an intermediary acts on them in reasonable ways, will expedite data transfer to the client. This creates a problematic incentive for clients to lie to the intermediary. For example, a client might attempt to get better performance by claiming to always have a stalled buffer.

In a worst-case scenario, unchecked expediting like this could be used to make a DDoS more effective by prioritizing the attack traffic.

There are a number of approaches to this, like limiting expedites per IP, or even punishing mendacious clients with a lower service priority. But the actual issue should be pointed out.

It might be time for a `Security Concerns` section of the document.

**Comment by wilaw** [comment]
We have a security considerations section in the doc, as quoted below. What language would you propose adding to address your concern above?

------------------------------

Note: Security considerations - we are not naive in assuming that all clients are benevolent. However, we don't believe the spec exposes any security issues that are not already exposed to an edge server which answers all requests. A number of steps have been taken to mitigate security concerns:

- The ‘nor’ key value must be a relative path to the current request. This makes it harder to inject false requests to arbitrary objects.
- Only one object can be requested by the ‘nor’ key value -  this lowers amplification opportunity.
- All requests to the server are optionally executed by the server, meaning that a server can ignore them for security concerns (such as a rate-based threshold being exceeded) and still be compliant with the specification.
-

**Comment by wilaw** [comment]
Group added a bullet point under server behaviors section

"Servers should be aware that malicious clients may send false key data with the objective of either attacking the server or gaining an unfair delivery advantage. The server should validate incoming key data  before any performance impacting behaviors are executed"
