### ISSUE TITLE
Time window for throughput

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#3]
"The requested throughput that the client considers sufficient for delivery of the asset. For example, a client would indicate that the current segment, encoded at 2Mbps, is to be delivered at no more than 10Mbps, by using rtp:10000."

Stockhammer - This is unclear, as throughput always relates to a window. Is it related to the object duration?

Law - It is the throughout that the player wants assigned to the current object that is being requested. It is not a function of the objects duration.

Stockhammer - But again, the window of measurement is the object duration, correct?

Law - It is not the objects duration, it is the time taken to deliver the object. If a 4s video segment is delivered in 1s, then we care about the throughput measured over that 1s that it takers to deliver the object.

**Comment by acbegen** [comment]
Requested tput sounds incorrect IMO. Based on the definition, I think it should rather say "Requested max sending rate". If there is a congestion on the server or somewhere on the network, server's TCP (or any other transport protocol) may not allow to send at the requested rate anyway. So, the client should only indicate the max value and the name should reflect that.

**Comment by wilaw** [comment]
Group accepted inclusion of "maximum" in definition, but prefers to keep "throughput" versus "sending rate"
