### ISSUE TITLE
Query parameter needs reference and detail

### ISSUE THREAD

**Issue by alficles** [cta-wave/common-media-client-data#30]
The reference to the query parameter needs to be fleshed out. It appears that we're assuming the query string will be in `application/x-www-form-urlencoded` format. We should find the appropriate reference and insert it. Here's the "living document" version, but I think we can locate a published version to cite: https://url.spec.whatwg.org/#application/x-www-form-urlencoded

Second, we need to discuss how the added text should be combined with an existing query string, if one is present. I suggest: "If the request already bears a query string, then an ampersand followed by the encoded Common-Media-Client-Data field should be appended."

This scheme could cause trouble if the query form is used on a request that has a query that is not `application/x-www-form-urlencoded`, but I don't really see a way around that.

**Comment by wilaw** [comment]
Reference added to URLEncoding spec. Also added following text
"If the data payload is transmitted as a query argument, then the entire payload string MUST be URLEncoded per [1]. Data payloads transmitted via headers MUST NOT be URLEncoded. "

Added "If the request already bears a query string, then an ampersand followed by the encoded Common-Media-Client-Data field should be appended." text to spec.
