### ISSUE TITLE
Server processing requirements include requirements on client

### ISSUE THREAD

**Issue by LPardue** [cta-wave/common-media-client-data#35]
In the server requirements section is 

> The client SHOULD NOT depend upon any pre-fetch action being taken - it is merely a
request for optimization.

which seems like it could be out of place

**Comment by wilaw** [comment]
Agreed. We moved the text "The client SHOULD NOT depend upon any pre-fetch action being taken - it is merely a request for such a pre-fetch to take place." in to the key/value definition table, which is the appropriate client requirements section.
