### ISSUE TITLE
Is there a strong reason for key name case sensitivity?

### ISSUE THREAD

**Issue by LPardue** [cta-wave/common-media-client-data#37]
The doc says:

> All key names are case-sensitive.

Given that the defined parameters are all lowercase, is there a good reason for this requirement?

**Comment by alficles** [comment]
I think this is an implementation of Postel's "be conservative in what you do". I'd be happy with a `MUST produce` lower-case and I believe Structured Headers requires it.

**Comment by wilaw** [comment]
Group consensus to maintain case-sensitivity for keys, for both header and QA methods of transmission.
