### ISSUE TITLE
Encoded bitrate question

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#4]
re "The encoded bitrate of the audio or video object being requested. This may not be known precisely by the player, however it MAY be estimated based upon playlist/manifest declarations."

Stockhammer - The encoded bitrate of the audio or video object being requested. This may not be known precisely by the player, however it MAY be estimated based upon playlist/manifest declarations.

Law - I don't understand your question here. This is simply the encoded bitrate of the object, as expressed in the manifest or playlist.

Stockhammer - But the manifest says bandwidth and minBufferTime. So you want this value to be added? The encoded bitrate is always expressed over a window

**Comment by wilaw** [comment]
Added language "This may not be known precisely by the player, however it MAY be estimated based upon playlist/manifest declarations."

Proposed to delete field "encoded bitrate", since this is only used by CDN to estimate duration and we are passing duration directly.

**Comment by pankaj-giter** [comment]
The field for 'encoded bitrate' is interesting for a CDN for reasons such as:
1/ Knowing what is being delivered within a geo, ASN
2/ Popularity graph of encoded bitrates and making it visible to customer
3/ Associating any delivery issues to specific bitrates
4/ etc.

**Comment by dhassoun** [comment]
this has been re-added back to the document after discussion as there are good reasons supporting this. 

the accuracy should be sufficient for the value attained by the CDN.

NOTE:  Removing Object size as it can be determined by the bitrate and duration by the server - likely more accuratel
