### ISSUE TITLE
Vary

### ISSUE THREAD

**Issue by mnot** [cta-wave/common-media-client-data#42]
It's probably worth mentioning in the Server processing requirements that if the response is cacheable (and presumably it will be), Common-Media-Client-Data probably should _not_ be listed in the `Vary` header.

**Comment by wilaw** [comment]
Good point. We will add that.

**Comment by wilaw** [comment]
Added server processing requirement "The Common-Media-Client-Data header MUST not be included in the Vary header [5] sent by an origin server."

**Comment by wilaw** [comment]
Agreed during group call.
