### ISSUE TITLE
Header or Query Arg?

### ISSUE THREAD

**Issue by mnot** [cta-wave/common-media-client-data#43]
> The server MAY assume that the payload is held as either a header or a query arg, but
never both at the same time.

How's that going to work? Specifically, how will a generic client with no special knowledge of the server know what form to send if the server only supports one of the two, but at the same time:

> A request can carry a Common-Media-Client-Data header or a Common-Media-Client-Data query arg, but it MUST NOT carry both.

? It sounds like that's out-of-band configuration, which isn't great.

**Comment by wilaw** [comment]
The server must support both forms. The client may choose to send either form, whichever is most convenient for it. No out-of-band communication is required. The client is restricted from using both forms in the same request.  The server is not expected to be sufficiently stateful that it resolves the dual send down to a single data set. If a non-conforming client sends data on both forms, then the server will log it twice.

**Comment by mnot** [comment]
Ah, OK. An explicit requirement that servers have to support both forms would probably help (unless I missed it?).

**Comment by wilaw** [comment]
Agreed. Added following text to document

"The server MUST support both the header and query argument methods of data transmission. The server MAY assume that the payload is transmitted either as a header or a query arg, but never both at the same time for a given request. "

**Comment by mnot** [comment]
LGTM, thanks.
