### ISSUE TITLE
mtp - multiple connections to the same server

### ISSUE THREAD

**Issue by wpower-cdn** [cta-wave/common-media-client-data#46]
From Measured throughput (mtp): 
 "The throughput existing between client and server, as
measured by the client. This value, however derived,
SHOULD be the value that the client is using to make its
next Adaptive Bitrate switching decision. If the client is
connected to multiple servers concurrently, it must take
care to report only the throughput measured against the
receiving server."

Is it assumed that if the client has multiple concurrent connections to a single server, the mtp is based on the aggregate throughput from all the concurrent connections to that server?  I think that is the intent, but it might be worth making that explicit.

**Comment by wilaw** [comment]
Added :"If the client has multiple concurrent connections to the server, then the intent is that this value communicates the aggregate throughput the client sees across all those connections. "

**Comment by mnot** [comment]
It might be worth mentioning that the browser has no idea whether they're the same physical server.
