### ISSUE TITLE
Add bufferlength as a field

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#48]
In early POCs involving this spec, the most requested missing feature is a real-time plot of player buffer length. We took out buffer length early on, as it is hard to interpret a low buffer length as being an indicator of a problem (since all player buffers are 0 at start-up and seek). However if we acknowledge that there are uses to monitoring buffer length (general player health) and that the Buffer State field can be used to explicitly signal rebuffering problems, then it would be good to reintroduce buffer length as a new field

Buffer length - bl - Integer - Buffer value in milliseconds. 

Since players often have two buffers (one for video and one for audio), the length transmitted in this field should be appropriate to the object being requested. If the object type ‘ot’ key is sent along with this key, then the ‘bl’ value refers to the buffer associated with the particular object type. If no object type is communicated, then the buffer length applies to the current session.

The buffer length field SHOULD be sent each time the Buffer state field is sent.

**Comment by wilaw** [comment]
Also, should bufferlength replace the deadline 'dl' field? Argument is that players have no existing workflow to calculate a deadline, but they all know the state of their buffers. In the dash.js prototype implementation, they simply reported bufferlength as a proxy for deadline anyway.

**Comment by dhassoun** [comment]
I'm just trying to think if an abr switch avoidance is more related to
deadline or bufferlength.

To me it seems like bufferlength is fine and could remove dl but in theory
dl would offer an option for more hinting but may be very difficult to
accurately determine.

[ Sent from mobile device - please excuse brevity or typos ]

**Comment by wilaw** [comment]
Discussion around fingerprinting. Mainly a concern for native players which can be instantiated via javascript. Could we make a normative statement that implementers of such native players SHOULD not include the buffer-length parameter (and perhaps others)?

**Comment by wilaw** [comment]
Added new Buffer length 'bl' key. Consensus to keep deadline as it applies to objects that bl does not, such as manifests.
