### ISSUE TITLE
Device ID domain (Comment from Streaming Video Alliance)

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#53]
Below is a comment on draft CTA-5004 Common Media Client Data from the Streaming Video Alliance:

Device ID – needs a domain for that – there is a sort of device std for Device ID used by Chrome or everyone will report different device types - HTTP ClientID would be fine

**Comment by wilaw** [comment]
For client privacy concerns, the Device ID key has been removed from the spec. See https://github.com/cta-wave/common-media-client-data/issues/45 for details.
