### ISSUE TITLE
Deadline/Object Duration/Buffer all seem to indicate buffer distress (Comment from the Streaming Video Alliance)

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#54]
Below is a comment on draft CTA-5004 Common Media Client Data from the Streaming Video Alliance:

Deadline/Object Duration/Buffer state=3 – these things seem to indicate a buffer distress in 3 places could they not be one ?

**Comment by wilaw** [comment]
Deadline indicates the time by when a player must receive the data to avoid a problem. This may be less than the existing buffer length. The object duration is fixed and is independent of any distress situation.

Let's consider a player with 6s segment for audio and video, with a 5s video buffer, 3s audio buffer and 2s of minimum decode buffer and a target buffer of 12s.  On the video segment request, it would report

dl: 3000
d: 5000
bs: 3

When it recovers to a 15s buffer, it would indicate
dl: 13000
d: 5000
