### ISSUE TITLE
Why Next Objects/Next range (Comment from Streaming Video Alliance)

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#55]
Below is a comment on draft CTA-5004 Common Media Client Data from the Streaming Video Alliance:

Next Objects/Next range  - not sure why we need these ? isn’t this already in ether the file request or byte range ? (i.e. I am unlikely to request file 1, 4, 7 but will do 1,2,3,4)

**Comment by wilaw** [comment]
There is
1. No rigorous naming scheme for segments which will allow a CDN to write a regex for prefetching based purely on the requested URL.
2. Byte ranges often vary in size with each request
3. No existing standard means of indicating an object to be prefetched.
4. Segment names may not be predictable and/or be obfuscated.
5. A DASH Segmentimeline/$time$ request flow is very difficult to predict from the server-side only.
