### ISSUE TITLE
Playback rate question (Comment from Streaming Video Alliance)

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#56]
Below is a comment on draft CTA-5004 Common Media Client Data from the Streaming Video Alliance:

Playback Rate – why does this matter ? is this when you FF you increase BW use ? so is predictively looking at video

**Comment by wilaw** [comment]
It matters in the cases of
1. Fast-forward in which a buffer is being consumed at a rate greater than 1 (which helps interpret any buffer length data sent)
2. Low latency players which use rate adjustment to hold a precise time-behind-live. 
We  indicate that the field SHOULD only be sent when its value is != 1, which in practice means this field will rarely be sent.
