### ISSUE TITLE
Buffer state: why not communicating the level (number of seconds)

### ISSUE THREAD

**Issue by guiomme** [cta-wave/common-media-client-data#57]
As other suggested, the current proposal related to "Buffer state" is subject to interpretation. It may therefore add complexity to the player and be pretty useless to the server. Why not simply communicate the buffer level in e.g. number of seconds of video?

**Comment by wilaw** [comment]
See https://github.com/cta-wave/common-media-client-data/issues/48

The new "bl' bufferlength key was added.
