### ISSUE TITLE
Inclusion of Quality Metric Key (Comment from the Streaming Video Alliance)

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#58]
Below is a comment on draft CTA-5004 Common Media Client Data from the Streaming Video Alliance:

Inclusion of a key for quality metric Q information (either derived somehow by player, or provided by third party agents situated along-side the players or provided within the manifest itself (a la Netflix VMAF scores), i.e. allow a data channel for player or third parties to plug in and provide quality metrics that are not necessarily a derivation of readily available QoS-related transmission characteristics such as bitrate, throughput, etc., rather enable plugging in of quality metrics that may be derived by third-party algorithms)

**Comment by wilaw** [comment]
We do not see a sufficiently developed standard available today for quality metrics to be a) Added to manifests/playlists or b) for players to calculate this in a no-reference implementation. If this standard were to be developed, then we would consider adding it as a reserved key.

If an implementer wishes to transmit quality data that is unique to their application, they can do so using a custom key, such as

com.customer-quality: "my-quality-metric"

**Comment by slhck** [comment]
With respect to CTA-2066 Section 9, it would be possible to transmit calculated P.1203 quality values as quality metric data in CMCD.

In principle, this would even allow for sending dedicated values for audio quality, video quality, audiovisual quality (all on a per-1-second basis), and overall aggregated quality (including the effect of stalling), which would require different fields — not just one `q`.

This metric *can* be calculated purely on the client-side, in a no-reference style.

**Comment by slhck** [comment]
An alternative would be specifying `q` as a quality metric value and `qt` (or similar) as the type of quality metric, for which a list of known metrics can be specified.
