### ISSUE TITLE
Inclusion of Playout Error Key (Comment from Streaming Video Alliance)

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#59]
Below is a comment on draft CTA-5004 Common Media Client Data from the Streaming Video Alliance:

Inclusion of a key for playout error information (derived by players during playout)

**Comment by wilaw** [comment]
Not our intent to replace existing commercial client reporting, which already captures this information. More importantly no consistency between players for error codes (no standard exists), so CDNs cannot react consistently.

If the player wants to communicate error codes, it can always do that with a custom field, which si already supported by the spec.

com.customer-errors: "my-error-code-string"

If we have standardized error messages from players, then we would look at a reserved field to report these in v2. We support the development of such standardized error codes by the SVA.
