### ISSUE TITLE
Add Relevant CTA-2066 Session Metrics (contribution from the Streaming Video Alliance)

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#62]
This comment is a contribution from the Streaming Video Alliance Quality of Experience WG.

Add (relevant) CTA-2066 Session Metrics to CMCD, for example:

initialStartupTime
playbackStallCount
playbackStallDuration
bitsPlayed

**Comment by wilaw** [comment]
Initial request was to add all CTA-2066 QoE metrics.
Note that CTA-2066 metrics are mostly not known by the player . The CTA spec requires the player to emit events and expose properties which a 3rd party analytics client uses to generate these metrics. 

@David - his players do not keep track of counts, or stalls, bits played. On a whole, players don't calculate these. Their responsibility is event dispatch.

initialStartupTime - can be estimated by examining existing CMCD data (subtract wallclock time of buffer length >= 1s from manifest request time). Des not work for preloaded manifests. 
playbackStallCount - can be calculated by examining existing CMCD data (count number of bs counts in a given window)
playbackStallDuration - can be estimated by examining existing CMCD data (sum deltas of wallclock time of bs receipt until buffer level recovered).
bitsPlayed - can be estimated by examining existing CMCD data (sum object sizes requested by player)

Could a subgroup establish (register) a custom sub-set of keys that did report CTA-2066 metrics (or any other metrics for that matter). For example:

org.streamingvideoalliance.cta-2066-initialStartupTime: 2100

Consensus: do not add CTA-2066 metrics directly, but do encourage the establishment of industry specific custom keys for relaying advanced QoE and other metrics.
