### ISSUE TITLE
We need a way to sign CMCD headers and parameters.

### ISSUE THREAD

**Issue by alficles** [cta-wave/common-media-client-data#65]
There needs to be a way for a player to sign the data it is providing to the CDN. This needs to be carefully thought through to consider both tamper-proof and open devices.

**Comment by piersoh** [comment]
This IETF draft, [HTTP Message Signatures](https://httpwg.org/http-extensions/draft-ietf-httpbis-message-signatures.html#name-application-of-http-message), looks like it should provide for such functionality. Key distribution to clients is often a bit challenging, but it is probably out of scope here.

**Comment by PCaponetti** [comment]
This seems to be outside of the concerns of CMCD, and can be accomplished by other IETF drafts or things like CTA-CAT
