### ISSUE TITLE
Which keys are permitted on each request?

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#7]
Filed on behalf of Thomas Edwards

re "For example, a ‘br’ key on a manifest request is inappropriate and should be omitted"

We should be specific about what is permitted on what kind of request, perhaps in a table.

**Comment by wilaw** [comment]
Thomas to propose some language.

**Comment by NEOAdvancedTechnology** [comment]
"Note: Some keys may not be appropriate to be used on some requests, for example, a ‘br’ (bitrate) key on a manifest request."

**Comment by NEOAdvancedTechnology** [comment]
Expanded and perhaps a bit clearer, clean of normative language: "Note: Although any key may be optionally used on a request, some keys might not sensible to be used on some requests, for example, a ‘br’ (bitrate) key on a manifest request."

**Comment by wilaw** [comment]
Group debated and concluded with "Other keys should be applied where they have contextual meaning. For example, a ‘br’ (bitrate) key on a manifest request is inappropriate and could be omitted".
