### ISSUE TITLE
Lack of consistency in describing the type of requests for which a CMCD field can be included

### ISSUE THREAD

**Issue by mgreve-akamai** [cta-wave/common-media-client-data#73]
* For the encoded bitrate field (br), it is specified as: "The encoded bitrate of the audio or video object being requested".
* For the buffer length field (bl), it is specified as: "This key SHOULD only be sent with an object type of ‘a’, ‘v’ or ‘av’".

The latter description is very clear, but the former is not.

In general, it would be helpful to have a clear description for the types of requests where each field should be sent. For instance, in practice we have seen players that send an object duration field on manifests... Hence, if the object duration field has specified that it was only to be sent for an object type of 'a', 'v' or 'av', then I think such potential issues could be avoided. One thought that came to mind was to have another column in the CMCD field table describing the types of objects for which each field should be sent.

**Comment by PCaponetti** [comment]
I went through the spec and found all the fields that do not specify type, they are:

- Encoded bitrate: Possibly add a set of types that have bitrates.
- Buffer starvation: Possibly add a set of types that can be buffered.
- Streaming format: Possibly only on the video bytes?
- Top bitrate: Possibly add a set of types that have bitrates.
- CMCD version: For v2 will likely need this on all requests.

Here are the ones that I don't see a need to specify object types the field is valid for:
- Content ID: Might add a SHOULD to send with all requests to help with link-ability.
- Playback rate: Playback rate should always be global to the playback and not specific to one object type as part of that
- Measured throughput: throughput shouldn't depend on the content of the bytes.
- Requested maximum throughput
- Deadline
- Next object/range request
- Session ID: Might add a SHOULD to send with all requests to help with with link-ability.
- Stream type
- Startup

More tactically: recently the idea of a set of types with an "intrinsic duration" was added to the object duration field, and that maybe should be carried over to buffer length as there were more types noted.

**Comment by PCaponetti** [comment]
Made the suggested changes. Notes:
- I only added low latency HLS for streaming format. Might be missing some other popular format(s).
- Upon second look I disagreed with suggesting that streaming format should be sent on all requests as the use cases are satisfied in post-processing where requests are linkable by session ID.

**Comment by wilaw** [comment]
Added the language "_Object types of  ‘a’, ‘v’, and ‘av’ usually have intrinsic bitrates and an object type of ‘o’ may have an intrinsic bitrate_" to the Encoded Bitrate definition.
