### ISSUE TITLE
Object duration specified on playlist/manifest - is this valid?

### ISSUE THREAD

**Issue by mgreve-akamai** [cta-wave/common-media-client-data#74]
We have seen players sending an object duration field on manifests/playlists (see also https://github.com/cta-wave/common-media-client-data/issues/73). It is unclear how should a value should be interpreted. We assume that the spec intends only this field to be sent for objects of type 'a', 'v', 'c', 'av' and 'tt'. Is this understanding correct?

**Comment by wilaw** [comment]
The intent was that the duration value should only be sent for objects which have an intrinsic duration  - namely the a', 'v', 'c', 'av' and 'tt' types as you indicate. 


The spec currently says " ..the playback duration in milliseconds of the object being requested". This should be improved to indicate that this value should only be sent with requests for objects that have an intrinsic media duration.

**Comment by wilaw** [comment]
Document edited to include the text

> This value MUST NOT be sent for objects which do not have an intrinsic duration. Object types of  ‘a’, ‘v’, ‘av’, ‘tt’, ‘c’ and ‘o’ usually have intrinsic durations.
