### ISSUE TITLE
Bug re. incorrect field name in example 3 in section 6.2 of the CMCD spec

### ISSUE THREAD

**Issue by mgreve-akamai** [cta-wave/common-media-client-data#75]
Example 3 in 6.2 uses the field name "b", which presumably should have been "bs". See the part highlighted in bold below:

6.2 Corresponding Query Arg examples
1. ?CMCD=sid%3D%226e2fb550-c457-11e9-bb97-0800200c9a66%22
2. ?CMCD=br%3D3200%2Cbs%2Cd%3D4004%2Cmtp%3D25400%2Cot%3Dv%2Crtp
%3D15000%2Csid%3D%226e2fb550-c457-11e9-bb97-
0800200c9a66%22%2Ctb%3D6000
3. ?CMCD=**b**%2Crtp%3D15000%2Csid%3D%226e2fb550-c457-11e9-bb97-
0800200c9a66%22

Link to spec: https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5004-final.pdf

**Comment by wilaw** [comment]
Fixed.
