### ISSUE TITLE
Add a 'rid' request ID key in v2

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#77]
A request ID is a useful construct for request tracing.

**Comment by PCaponetti** [comment]
Note the overlap with the CTA group for Streaming Media Tracing. 

(I know you know because you are in the group, just noting here for others 😄)

**Comment by PCaponetti** [comment]
This overlaps too squarely with streaming media request tracing, and also there is a fairly common x-request-id header already.
