### ISSUE TITLE
Use ACCEPT header to avoid preflight request

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#9]
[Filed on behalf of Christian at Akamai]
You mention that the server should provide relevant CORS headers to allow a JavaScript player to set the Common-Media-Client-Data HTTP header. This will require an additional preflight request and hence an additional RTT for each request (at least). Have you considered making the data a part of the Accept header which does not require a preflight request? In any case, it may be a good idea to mention the problem in the document.

**Comment by wilaw** [comment]
I have concerns with overriding the ACCEPT header and using it at wide scale for a purpose for which it was not intended. The pre-flight problem is known and that is why the option to send the data as a query-arg is made available. Our expectation is that non-MSE players will use custom headers and MSE-based players will use query-args.

**Comment by cwmos** [comment]
Thank you for filing this request!

I agree that using the ACCEPT header is somewhat a hack that may not be good to put into a standard. Still, the standard mentions the server should send CORS headers. So it may be a good idea to include a small discussion on the problem and the recommended behavior for JavaScript and non-JavaScript players.

**Comment by wilaw** [comment]
Added language "Note: that usage of a custom header from a Javascript player will trigger a preflight OPTIONS request before each media object request. This will lead to an increased request rate against the server.   Our expectation is that non-MSE players will use custom headers and MSE-based players will use query-args."
