### ISSUE TITLE
Separate startup cases

### ISSUE THREAD

**Issue by nbjensen** [cta-wave/common-media-client-data#90]
Currently, the su flag indicates some sort of startup where the object is needed urgently due to startup, seeking or recovery after a buffer-empty event.

It would be very helpful to also signal why we are in a startup phase, e.g. where the stream just started, whether there was a seek or a recovery.

**Comment by wilaw** [comment]
Added text to disambiguate SU from sta=s

> Key is included without a value if the object is needed urgently due to startup, seeking or recovery after a buffer-empty event. The player reports this key as true until its buffer first reaches the target buffer for stable playback. This key MUST be sent if it is TRUE. 
> Note: the starting State 's' is valid until the player renders media for the end user, which may be different from when the target buffer has been reached. As a result, the 'su'  = TRUE and 'sta' = 's' are not expected to align on a timeline.

**Comment by gwendalsimon** [comment]
Regarding the key "su", instead of "startup", it could be possible to name it "service urgency" or "stream urgency".
(it is really a minor point)

**Comment by wilaw** [comment]
>  it could be possible to name it "service urgency"

+1
