### ISSUE TITLE
Identify requests received out of order on the server

### ISSUE THREAD

**Issue by nbjensen** [cta-wave/common-media-client-data#91]
Currently, it is not possible to determine the order that requests are made in by the player as part of a playback session. The server only knows when a request was received on the server and under certain conditions requests can arrive out of order (e.g. parallel connections or several servers).

This can make it tricky to analyze an event such as a rebuffer.

It would be helpful to add a way to identify the ordering that requests are made in, e.g. a running counter.

**Comment by PCaponetti** [comment]
A monatomic timer since playback start time could have multiple uses, even knowing about the noise that is injected with variable latency hops to CDN and/or origins.

**Comment by PCaponetti** [comment]
The intended affect could be gained by using the new timestamp field more frequently (on all requests), but requiring this would be too heavy handed.
