### ISSUE TITLE
Expand Streaming format with specific keys for other protocols

### ISSUE THREAD

**Issue by PJSP** [cta-wave/common-media-client-data#95]
Section 3.3 "Reserved keys" specifies four options in the `Streaming format` (`sf`), being 
```
d = MPEG DASH
h = HTTP Live Streaming (HLS)
s = Smooth Streaming
o = other
```
With the rise of HESP ([High Efficiency Streaming Protocol](https://datatracker.ietf.org/doc/draft-theo-hesp/)) usage, we would want to be able to identify this protocol beyond the capabilities provided in `other`.  We would propose expanding the value definition to contain:
```
e = High Efficiency Streaming Protocol (HESP)
```
We expect using `hesp` as a fully written out value would be longer than desired.

**Comment by wilaw** [comment]
Added

d = MPEG DASH [10]
h = HTTP Live Streaming (HLS) [11]
e = HESP [12]
ld = Low latency DASH [10]
l3 = Low latency low delay DASH (L3D)
lh = Low Latency HLS [11]
o = other
s = Smooth Streaming [13]
